source :rubygems

gemspec

gem "factory_girl_rails", "3.5.0", :require => false
gem "rspec-rails"
gem "shoulda-matchers"
gem "faker"
gem "debugger"
gem "spork"

gem "teabag"

gem "guard"
gem "guard-rspec"
gem "guard-spork"
gem "guard-bundler"
gem "guard-teabag"
gem "rb-fsevent"
gem "terminal-notifier-guard"